services:
  # PostgreSQL database
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: hearts_game
      POSTGRES_USER: hearts_user
      POSTGRES_PASSWORD: hearts_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hearts_user -d hearts_game"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Backend service
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://hearts_user:hearts_password@db:5432/hearts_game
      PORT: 3001
      NODE_ENV: development
      FRONTEND_URL: http://localhost:3000
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /app/dist

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://localhost:3001
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next

volumes:
  postgres_data: